name: flutter_toolkit
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  cross_file: any
  desktop_drop: any
  cupertino_icons: ^1.0.6
  analyzer_x:
    path: ./plugin/analyzer_helper

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

